name: Build and deploy Python app to Azure Web App

env:
  AZURE_WEBAPP_NAME: Delimate  # Your Azure Web App name
  PYTHON_VERSION: '3.8'        # Python version to use

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          # cache: 'pip'  # Enable if you want pip caching

      - name: Create and activate virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        run: pip install -r requirements.txt

      # Optional: Add your test steps here

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            .
            !venv/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: none
    environment:
      name: 'Development'  # Ensure this environment exists in your GitHub repo settings

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: python-app
          path: .

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
