name: Build, Push Docker image and Deploy to Azure Web App

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build Docker image
      run: |
        IMAGE_TAG=${{ secrets.DOCKERHUB_USERNAME }}/my-image-name:${{ github.sha }}
        docker build -t $IMAGE_TAG .

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Push Docker image to Docker Hub
      run: |
        IMAGE_TAG=${{ secrets.DOCKERHUB_USERNAME }}/my-image-name:${{ github.sha }}
        docker push $IMAGE_TAG

    - name: Deploy to Azure Web App for Containers
      uses: azure/webapps-deploy@v2
      with:
        app-name: Delimate   # Replace with your Azure Web App name
        images: ${{ secrets.DOCKERHUB_USERNAME }}/my-image-name:${{ github.sha }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
