name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          IMAGE_TAG=my-image-name:$(date +%s)
          docker build . -f Dockerfile -t $IMAGE_TAG
          echo "Built image $IMAGE_TAG"

      # Optional: Log in to Docker Hub or Azure Container Registry (ACR)
      # - name: Log in to Docker Hub
      #   uses: docker/login-action@v2
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}

      # - name: Push Docker image
      #   run: |
      #     docker push $IMAGE_TAG

      # Optional: Deploy to Azure Web App for Containers
      # - name: Deploy to Azure Web App
      #   uses: azure/webapps-deploy@v2
      #   with:
      #     app-name: ${{ env.AZURE_WEBAPP_NAME }}
      #     images: $IMAGE_TAG
      #     publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
